mysql:
  image: mysql
  ports:
    - 3306:3306
  volumes:
    - /conf:/etc/mysql/conf.d
  net: "host"
  command: --default-authentication-plugin=mysql_native_password
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw


